### ISSUE TITLE
E.R.D.

### ISSUE THREAD

**Issue by sarahholder** [nss-evening-cohort-11/nutshell-ewoks-droids#56]

**Comment by sarahholder** [comment]
![Screen Shot 2020-04-21 at 9 44 15 PM](https://user-images.githubusercontent.com/59459651/79937915-c066bd80-8420-11ea-8627-5f1aaa99375c.png)

**Comment by sarahholder** [comment]
<img width="1007" alt="Screen Shot 2020-04-22 at 12 01 06 AM" src="https://user-images.githubusercontent.com/59459651/79942530-aa5efa00-842c-11ea-9493-c065b3d2c205.png">

**Comment by sarahholder** [comment]
<img width="788" alt="Screen Shot 2020-04-22 at 12 46 00 AM" src="https://user-images.githubusercontent.com/59459651/79945072-ae8e1600-8432-11ea-8e1b-7bedb448a85e.png">

**Comment by ToddSpainhour** [comment]
![missions-erd-v2](https://user-images.githubusercontent.com/59629794/80328176-2d54cb80-8804-11ea-80e6-c6942bc232ef.JPG)
